### ISSUE TITLE
There is no more masking for sprites it makes a square with the whole image

### ISSUE THREAD

**Issue by Benraay** [Chocolate-Dinosaur/UIFX#16]
like you can see on these images when outline is active i'm loosing rounded edges this happens only in last 1.6.0 version
<img width="1326" alt="without outline" src="https://github.com/Chocolate-Dinosaur/UIFX/assets/734553/89f336a7-ac3c-44f4-a6ca-b6bce91376c3">
<img width="1349" alt="with outline" src="https://github.com/Chocolate-Dinosaur/UIFX/assets/734553/b3922bac-4aaa-4e43-a8a0-ea865a6c7a11">

**Comment by ChocDino-Andy** [comment]
This should now be solved in 1.6.1, thanks for reporting the issue!
